#Linear Algebra

NumPy adalah package array tujuan umum. Ini menyediakan objek array multidimensi berkinerja tinggi, dan alat untuk bekerja dengan array ini. Ini adalah standard package untuk komputasi ilmiah dengan Python. Numpy pada dasarnya digunakan untuk membuat array n dimensi.

In [14]:
import numpy as np

In [15]:
A = [[1, 3, 5], [7, 12, 21], [5, 18, 3]]
B = [13, 123, 51]

In [16]:
np.linalg.solve(A,B)
#x = 23.625 
#y = -3.75
#z = 0.125

array([23.625, -3.75 ,  0.125])

###Vector
Vektor dibangun dari komponen, yang merupakan bilangan biasa. Kita dapat menganggap vektor sebagai daftar bilangan, dan aljabar vektor sebagai operasi yang dilakukan pada bilangan dalam daftar. Dengan kata lain vektor adalah array 1-D numpy.

In [17]:
#Horizontal Vector
import numpy as np  
# creating list  
list1 = [10, 20, 30, 40, 50]  
# Creating 1-D Horizontal Array  
vtr = np.array(list1)  
vtr = np.array(list1)  
print("We create a vector from a list:")  
print(vtr)  

We create a vector from a list:
[10 20 30 40 50]


In [23]:
# Vertical list  
list1 = [[12], [40],  [6],  [10]]  
  
# Creating 1-D Vertical Array  
vtr = np.array(list1)  
  
vtr = np.array(list1)  
  
print("We create a vector from a list:")  
print(vtr)

We create a vector from a list:
[[12]
 [40]
 [ 6]
 [10]]


Below is the list of basic operations that we can perform in vector.

    Arithmetic
    Subtraction
    Multiplication
    Division
    Dot Product
    Scalar Multiplications


In [20]:
#Addition of 2 vector
list1 = [10,20,30,40,50]   
list2 = [11,12,13,14,15]    
   
vtr1 = np.array(list1)   
vtr2= np.array(list2)   
  
print("We create vector from a list 1:")   
print(vtr1)   
print("We create vector from a list 2:")   
print(vtr2)   
   
vctr_add = vtr1 + vtr2  
print("Addition of two vectors: ",vctr_add)  

We create vector from a list 1:
[10 20 30 40 50]
We create vector from a list 2:
[11 12 13 14 15]
Addition of two vectors:  [21 32 43 54 65]


In [25]:
#Addition of 2 vector
list1 = [10,20,30,40,50]   
list2 = [[11],[12],[13],[14],[15]]    
   
vtr1 = np.array(list1)   
vtr2= np.array(list2)   
  
print("We create vector from a list 1:")   
print(vtr1)   
print("We create vector from a list 2:")   
print(vtr2)   
   
vctr_add = vtr1 * vtr2  
print("Addition of two vectors: ",vctr_add)  

We create vector from a list 1:
[10 20 30 40 50]
We create vector from a list 2:
[[11]
 [12]
 [13]
 [14]
 [15]]
Addition of two vectors:  [[110 220 330 440 550]
 [120 240 360 480 600]
 [130 260 390 520 650]
 [140 280 420 560 700]
 [150 300 450 600 750]]


In [21]:
#Substraction 
list1 = [10,20,30,40,50]   
list2 = [5,2,4,3,1]  
   
vtr1 = np.array(list1)   
   
vtr2= np.array(list2)   
   
print("We create vector from a list 1:")   
print(vtr1)   
print("We create a vector from a list 2:")   
print(vtr2)   
  
vtr_sub = vtr1-vtr2  
print("Subtraction of two vectors: ",vtr_sub)  

We create vector from a list 1:
[10 20 30 40 50]
We create a vector from a list 2:
[5 2 4 3 1]
Subtraction of two vectors:  [ 5 18 26 37 49]


In [26]:
#multiplication
list1 = [10,20,30,40,50]   
list2 = [5,2,4,3,1]  
   
vtr1 = np.array(list1)   
   
vtr2= np.array(list2)   
   
print("We create vector from a list 1:")   
print(vtr1)   
print("We create a vector from a list 2:")   
print(vtr2)   
  
vtr_mul = vtr1*vtr2  
print("Multiplication of two vectors: ",vtr_mul)  
#Multiplication didapat dari : 
#vct[0] = x[0] * y[0]
#vct[1] = x[1] * y[1]

We create vector from a list 1:
[10 20 30 40 50]
We create a vector from a list 2:
[5 2 4 3 1]
Multiplication of two vectors:  [ 50  40 120 120  50]


In [27]:
#Division of 2 vector
list1 = [10,20,30,40,50]   
list2 = [5,2,4,3,1]  
   
vtr1 = np.array(list1)   
   
vtr2= np.array(list2)   
   
print("We create vector from a list 1:")   
print(vtr1)   
print("We create a vector from a list 2:")   
print(vtr2)   
  
vtr_div = vtr1/vtr2  
print("Division of two vectors: ",vtr_div)  

We create vector from a list 1:
[10 20 30 40 50]
We create a vector from a list 2:
[5 2 4 3 1]
Division of two vectors:  [ 2.         10.          7.5        13.33333333 50.        ]


In [29]:
# Vector Dot Product
#The vector dot product performs between the two same-length sequential vectors and returns the single dot product. 
#We will use the .dot() method to perform the dot product 
#vector c = x . y = (x1 * y1 + x2 * y2) 

list1 = [10,20,30,40,50]   
list2 = [5,2,4,3,1]  
   
vtr1 = np.array(list1)   
   
vtr2= np.array(list2)   
   
print("We create vector from a list 1:")   
print(vtr1)   
print("We create a vector from a list 2:")   
print(vtr2)   
  
vtr_product = vtr1.dot(vtr2)  
print("Dot product of two vectors: ",vtr_product)  
#(5*10)+(2*20)+(4*30)+(3*40)+(1*50) = 50+40+120+120+50 =380
print(vtr1[0])

We create vector from a list 1:
[10 20 30 40 50]
We create a vector from a list 2:
[5 2 4 3 1]
Dot product of two vectors:  380
10


In [30]:
#Vector scalar
#we multiply the scalar with the each component of the vector
list1 = [10,20,30,40,50]   
vtr1 = np.array(list1)   
       
scalar_value = 5  
       
print("We create vector from a list 1:")   
print(vtr1)   
      
# printing scalar value   
print("Scalar Value  : " + str(scalar_value))   
       
vtr_scalar = vtr1 * scalar_value  
print("Multiplication of two vectors: ",vtr_scalar)  

We create vector from a list 1:
[10 20 30 40 50]
Scalar Value  : 5
Multiplication of two vectors:  [ 50 100 150 200 250]


###Projection Vector

In [ ]:
# import numpy to perform operations on vector
import numpy as np

u = np.array([1, 2, 3]) # vector u
v = np.array([5, 6, 2]) # vector v:

# Task: Project vector u on vector v

# finding norm of the vector v
v_norm = np.sqrt(sum(v**2))	

# Apply the formula as mentioned above
# for projecting a vector onto another vector
# find dot product using np.dot()
proj_of_u_on_v = (np.dot(u, v)/v_norm**2)*v

print("Projection of Vector u on Vector v is: ", proj_of_u_on_v)

Projection of Vector u on Vector v is:  [1.76923077 2.12307692 0.70769231]


In [ ]:
(np.dot(u, v)/np.dot(v, v))*v

array([1.76923077, 2.12307692, 0.70769231])

In [ ]:
# Computing vector projection onto a Plane in Python:
import numpy as np
  
# vector u 
u = np.array([2, 5, 8])       
  
# vector n: n is orthogonal vector to Plane P
n = np.array([1, 1, 7])       
   
# Task: Project vector u on Plane P
  
# finding norm of the vector n 
n_norm = np.sqrt(sum(n**2))    
   
# Apply the formula as mentioned above
# for projecting a vector onto the orthogonal vector n
# find dot product using np.dot()
proj_of_u_on_n = (np.dot(u, n)/n_norm**2)*n
  
# subtract proj_of_u_on_n from u: 
# this is the projection of u on Plane P
print("Projection of Vector u on Plane P is: ", u - proj_of_u_on_n)

Projection of Vector u on Plane P is:  [ 0.76470588  3.76470588 -0.64705882]


###Basis

In [31]:
#Changing basis 
vec_old = [3, 4]
#Standard
w1 = [-2,4]
w2 = [2,1]
#Basis baru
vec_new = np.linalg.inv(np.array([w2,w1])).dot(vec_old)
print(vec_new)

[0.8 1.4]


In [32]:
vec_old = [1,2,3]
#Standard
w1 = [1, 0, 0]
w2 = [0, 0, 1]
w3 = [0, 1, 0]
#Basis baru
vec_new = np.linalg.inv(np.array([w1, w2, w3])).dot(vec_old)
print(vec_new)

[1. 3. 2.]
